name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Clone the repository
      - uses: actions/checkout@v3

        # Install Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

        # Make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install

        # Run linter and pytest
      - name: Run linter and pytest
        run: |
          make check